services:
  web:
    build: .
    ports:
      - "0.0.0.0:8003:8000"
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-false}
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///artful-one.db}
      - MEDIA_ROOT=/app/media
      - SKETCHY_MEDIA_ROOT=/app/sketchy-media
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - SESSION_COOKIE_DOMAIN=${SESSION_COOKIE_DOMAIN}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-true}
      - SENTRY_DSN=${SENTRY_DSN}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - PALM_API_KEY=${PALM_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - ./artful-one.db:/app/artful-one.db
      - ./media:/app/media
      - sketchy_media:/app/sketchy-media
      - ./staticfiles:/app/staticfiles
      - ./etc/config:/home/appuser/.config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sketchy_media:
