"""ICONS RPG Character Generator Library."""

from .rolltable import RollTable, rolltable_factory, rolltable_lookup
from .name_generator import random_super_name
from .icons_characters import (
    Power,
    Modifier,
    Ability,
    Abilities,
    Specialty,
    Super,
    d4,
    d6,
    two_d6,
    d10,
    icons_random_level,
    icons_random_origin,
    icons_random_abilities,
    icons_random_power,
    icons_random_powerset,
    icons_random_specialties,
    icons_random_super,
)
from .icons_kaiju import Monster, make_random_kaiju
from .icons_creatures import (
    make_bear,
    make_cat,
    make_cheetah,
    make_crocodile,
    make_dog,
    make_dog_guard,
    make_dolphin,
    make_eagle,
    make_electric_eel,
    make_elephant,
    make_gorilla,
    make_hippo,
    make_horse,
    make_human,
    make_lion,
    make_monkey,
    make_orca,
    make_python,
    make_rhino,
    make_shark,
    make_squid_giant,
    make_swarm,
    make_viper,
    make_whale,
    make_wolf,
    make_wolverine,
    make_apatosaurus,
    make_deinonychus,
    make_pterodactyl,
    make_triceratops,
    make_tyrannosaur,
)
from .cli import CREATURE_REGISTRY

__version__ = "0.1.0"
__all__ = [
    "RollTable",
    "rolltable_factory",
    "rolltable_lookup",
    "random_super_name",
    "Power",
    "Modifier",
    "Ability",
    "Abilities",
    "Specialty",
    "Super",
    "Monster",
    "d4",
    "d6",
    "two_d6",
    "d10",
    "icons_random_level",
    "icons_random_origin",
    "icons_random_abilities",
    "icons_random_power",
    "icons_random_powerset",
    "icons_random_specialties",
    "icons_random_super",
    "make_random_kaiju",
    "make_bear",
    "make_cat",
    "make_cheetah",
    "make_crocodile",
    "make_dog",
    "make_dog_guard",
    "make_dolphin",
    "make_eagle",
    "make_electric_eel",
    "make_elephant",
    "make_gorilla",
    "make_hippo",
    "make_horse",
    "make_human",
    "make_lion",
    "make_monkey",
    "make_orca",
    "make_python",
    "make_rhino",
    "make_shark",
    "make_squid_giant",
    "make_swarm",
    "make_viper",
    "make_whale",
    "make_wolf",
    "make_wolverine",
    "make_apatosaurus",
    "make_deinonychus",
    "make_pterodactyl",
    "make_triceratops",
    "make_tyrannosaur",
    "CREATURE_REGISTRY",
]
