# Generated by Django 6.0 on 2026-01-19 15:00

import django.contrib.staticfiles.storage
import pictures.models
from django.db import migrations, models


def set_existing_entries_to_false(apps, schema_editor):
    Entry = apps.get_model("blog", "Entry")
    Entry.objects.all().update(is_markdown=False)


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_photo_slug_maker"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_markdown",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_existing_entries_to_false),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2", "16/9"],
                blank=True,
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="height",
                null=True,
                pixel_densities=[1, 2],
                storage=django.contrib.staticfiles.storage.StaticFilesStorage(
                    base_url="/static/",
                    location="/home/bruce/work/artful-one-django/config/../staticfiles",
                ),
                upload_to="photos",
                width_field="width",
            ),
        ),
    ]
