# Generated by Codex on 2026-05-11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_photo_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=120)),
                ("social_url", models.URLField(blank=True, max_length=300)),
                ("company", models.CharField(blank=True, max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("brief", models.TextField(max_length=4000)),
                ("mailgun_status", models.CharField(blank=True, max_length=24)),
                ("mailgun_message_id", models.CharField(blank=True, max_length=255)),
                ("mailgun_error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
