# Generated by Django 5.2.15 on 2026-06-18 22:34

import shutil
from pathlib import Path

from django.conf import settings
import pictures.models
from django.db import migrations


def copy_existing_photo_files_to_media(apps, schema_editor):
    Photo = apps.get_model("blog", "Photo")

    def absolute_setting_path(setting_name):
        value = getattr(settings, setting_name, None)
        if not value:
            return None
        path = Path(value)
        if path.is_absolute():
            return path
        return Path(settings.BASE_DIR) / path

    media_root = absolute_setting_path("MEDIA_ROOT")
    if media_root is None:
        return
    source_roots = [
        root
        for root in (
            absolute_setting_path("STATIC_ROOT"),
            absolute_setting_path("BASE_DIR"),
        )
        if root is not None
    ]

    def copy_missing_tree(source, target):
        if source.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            if not target.exists():
                shutil.copy2(source, target)
            return

        if not source.is_dir():
            return

        for source_file in source.rglob("*"):
            if not source_file.is_file():
                continue
            target_file = target / source_file.relative_to(source)
            target_file.parent.mkdir(parents=True, exist_ok=True)
            if not target_file.exists():
                shutil.copy2(source_file, target_file)

    for image_name in (
        Photo.objects.exclude(image="")
        .exclude(image__isnull=True)
        .values_list("image", flat=True)
        .iterator()
    ):
        relative_path = Path(image_name)
        if relative_path.is_absolute() or ".." in relative_path.parts:
            continue

        media_path = media_root / relative_path
        for source_root in dict.fromkeys(source_roots):
            source_path = source_root / relative_path
            copy_missing_tree(source_path, media_path)
            copy_missing_tree(source_path.with_suffix(""), media_path.with_suffix(""))


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_entry_photo_entry_picture_size"),
    ]

    operations = [
        migrations.RunPython(
            copy_existing_photo_files_to_media,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2", "16/9"],
                blank=True,
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="height",
                null=True,
                pixel_densities=[1, 2],
                upload_to="photos",
                width_field="width",
            ),
        ),
    ]
