# Generated by Django 5.2.15 on 2026-06-18 22:34

import shutil
from pathlib import Path

from django.conf import settings
import pictures.models
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_entry_photo_entry_picture_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2", "16/9"],
                blank=True,
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="height",
                null=True,
                pixel_densities=[1, 2],
                upload_to="photos",
                width_field="width",
            ),
        ),
    ]
