# Generated by Django 6.0 on 2026-01-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog", "0008_photo_slug_maker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sketch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sketches",
                        to="blog.photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sketch",
                "verbose_name_plural": "Sketches",
                "ordering": ["name"],
            },
        ),
    ]
