# Generated by Django 6.0.2 on 2026-05-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
