# Generated by Django 6.0.2 on 2026-05-15 21:09

import django.db.models.deletion
from django.db import migrations, models


def create_scorpion_animation(apps, schema_editor):
    Animation = apps.get_model("sketches", "Animation")
    Animation.objects.get_or_create(
        slug="scorpion",
        defaults={
            "name": "Scorpion",
            "is_draft": False,
        },
    )


def delete_scorpion_animation(apps, schema_editor):
    Animation = apps.get_model("sketches", "Animation")
    Animation.objects.filter(slug="scorpion").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_entry_photo_entry_picture_size"),
        ("sketches", "0002_sketch_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("is_draft", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animations",
                        to="blog.photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animation",
                "verbose_name_plural": "Animations",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(create_scorpion_animation, delete_scorpion_animation),
    ]
