# Generated by Django 5.2.15 on 2026-07-23 18:45

import django.db.models.deletion
import sketches.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sketches", "0003_animation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SketchToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "prefix",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                (
                    "digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sketch_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sketch token",
                "verbose_name_plural": "Sketch tokens",
                "ordering": ["user_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkingSketch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "sketch_type",
                    models.CharField(
                        choices=[
                            ("d3", "D3"),
                            ("processing", "Processing"),
                            ("raw", "Raw"),
                        ],
                        max_length=10,
                    ),
                ),
                ("startup_js", models.TextField(blank=True, default="")),
                ("div_html", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_sketches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Working sketch",
                "verbose_name_plural": "Working sketches",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TemporarySketchMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        storage=sketches.models.temporary_sketch_media_storage,
                        upload_to=sketches.models.temporary_sketch_media_upload_to,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=sketches.models.default_temporary_media_expiry
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_sketch_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sketch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temporary_media",
                        to="sketches.workingsketch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temporary sketch media",
                "verbose_name_plural": "Temporary sketch media",
                "ordering": ["-created_at"],
            },
        ),
    ]
