# Generated by Django 6.0 on 2026-01-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RpgTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Internal canonical ID, e.g. names/2.1 or ad/ad1.1a",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the table"
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("columns", "Columns"),
                            ("select-one", "Select One"),
                            ("one-from-each", "One From Each"),
                            ("random-table", "Random Table"),
                            ("template", "Template"),
                        ],
                        help_text="How the table data should be interpreted",
                        max_length=32,
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Delimiter to join table columns",
                        max_length=32,
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False, help_text="Hide from public UI selectors"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Table data as list of lists (rows x columns)"
                    ),
                ),
                (
                    "addon",
                    models.JSONField(
                        blank=True,
                        help_text="Optional mapping of addon keys to table aliases, e.g. {'DEFAULT': '2.3', 'epithets': '2.3'}",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RPG Table",
                "verbose_name_plural": "RPG Tables",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="RpgTableAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="Alias used to reference the table",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="rpg.rpgtable",
                    ),
                ),
            ],
            options={
                "verbose_name": "RPG Table Alias",
                "verbose_name_plural": "RPG Table Aliases",
                "ordering": ["alias"],
                "indexes": [
                    models.Index(fields=["alias"], name="rpg_rpgtabl_alias_ac9a88_idx")
                ],
            },
        ),
    ]
